/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;
//import java.awt.*;
//import javax.swing.*;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import Conexion.ConexionMySQL;
import javax.swing.JOptionPane;
/**
 *
 * @author JULIAN
 */
public class Interfaz_empleados extends javax.swing.JInternalFrame {

     DefaultComboBoxModel modelociudad = new DefaultComboBoxModel();
     String idciudad;
     
     DefaultComboBoxModel modelocargo = new DefaultComboBoxModel();
     String idcargo;
     
     DefaultComboBoxModel modelotipo = new DefaultComboBoxModel();
     String idtipo;
       
    
    
    
    /**
     * Creates new form Interfaz_empleados
     */
    public Interfaz_empleados() {
        initComponents();
        inhabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void habilitar()
    {
    txtnombre.setEditable(true);
    txtnombre.setText("");
    txtapellido.setEditable(true);
    txtapellido.setText("");
    txtdireccion.setEditable(true);
    txtdireccion.setText("");
    txttelefono.setEditable(true);
    txttelefono.setText("");
    txtcorreo.setEditable(true);
    txtcorreo.setText("");
   
    txtuser.setEditable(true);
    txtuser.setText("");
    txtclave.setEditable(true);
    txtclave.setText("");
    btnguardar.setEnabled(true);
    btnbuscar.setEnabled(true);
    btncancelar.setEnabled(true);
    cbociudad.setEnabled(true);
    cbocargo.setEnabled(true);
    cbotipo.setEnabled(true);   
    
    
    } 
    
    void inhabilitar()
    {
    txtnombre.setEditable(false);
    txtnombre.setText("");
    txtapellido.setEditable(false);
    txtapellido.setText("");
    txtdireccion.setEditable(false);
    txtdireccion.setText("");
    txttelefono.setEditable(false);
    txttelefono.setText("");
    txtcorreo.setEditable(false);
    txtcorreo.setText("");
    cbociudad.setEditable(false);
    cbociudad.setEnabled (false);
    cbocargo.setEnabled(false);       
    cbotipo.setEnabled(false);
    
    txtuser.setEditable(false);
    txtuser.setText("");
    txtclave.setEditable(false);
    txtclave.setText("");
    
    btnguardar.setEnabled(false);
    btnbuscar.setEnabled(false);
    btncancelar.setEnabled(false);
   
    
    
    }
    void llenarciudad(){
   
        
          modelociudad.removeAllElements();
          
 
 try {
    
              
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
                
                
           PreparedStatement pstmt = null;
            ResultSet rs = null;
            String llenarciudad="select id_ciudad, descripcion as detalle  from ciudad ";             
                      
                
pstmt = cn.prepareStatement(llenarciudad);
rs = pstmt.executeQuery();
modelociudad.addElement(new mcombos("VER DEPARTAMENTOS","0"));
cbociudad.setModel(modelociudad);
while (rs.next()) 
{
    modelociudad.addElement(new mcombos(rs.getString("detalle"),rs.getString("id_ciudad"))); //aca meto el id q jalo con mcombos
   //  cbocargo.setModel(modeloCombo);
       }
}
catch(Exception e) {}
            
   //hay q declarar antes  DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(); en la parte de clases publicas
    
 
 
 
 
 }
    
void llenacargos()
            {

                modelocargo.removeAllElements();
try {
    
    
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
                
                
           PreparedStatement pstmt = null;
            ResultSet rs = null;
            String llenarciudad="select id_cargo, descripcion as detalle  from cargo_empleado ";             
                      
                
pstmt = cn.prepareStatement(llenarciudad);
rs = pstmt.executeQuery();
modelocargo.addElement(new mcombos("VER CARGOS","0"));
cbocargo.setModel(modelocargo);
while (rs.next()) 
{
    modelocargo.addElement(new mcombos(rs.getString("detalle"),rs.getString("id_cargo"))); //aca meto el id q jalo con mcombos
   //  cbocargo.setModel(modeloCombo);
       }
}
catch(Exception e) {}
            
   //hay q declarar antes  DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(); en la parte de clases publicas
    
 
 
    }    
    
     
    
    
    
    
    
    
     void llenar_combo() {
   modelotipo.removeAllElements();
       modelotipo.addElement(new mcombos("SELECCIONE TIPO USER","-1"));  
       modelotipo.addElement(new mcombos("ADMINISTRADOR","0"));
       modelotipo.addElement(new mcombos("VENDEDOR","1"));
       cbotipo.setModel(modelotipo);
        
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        cbocargo = new javax.swing.JComboBox();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbotipo = new javax.swing.JComboBox();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        cbociudad = new javax.swing.JComboBox();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CREACION DE EMPLEADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Direccion:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Apellido:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Ciudad:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Correo:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Cargo:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Usuario:");

        txtnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnombre.setText("jTextField1");

        txtapellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtapellido.setText("jTextField1");

        txtdireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtdireccion.setText("jTextField1");

        txttelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txttelefono.setText("jTextField1");

        txtcorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcorreo.setText("jTextField1");

        cbocargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbocargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocargoActionPerformed(evt);
            }
        });

        txtuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtuser.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Clave:");

        txtclave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtclave.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Tipo:");

        cbotipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipoActionPerformed(evt);
            }
        });

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        cbociudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbociudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbociudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)))
                                            .addComponent(jLabel7))
                                        .addGap(7, 7, 7))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbociudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnnuevo)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbocargo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btncancelar)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbotipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtclave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                            .addComponent(txtuser, javax.swing.GroupLayout.Alignment.LEADING)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnguardar)
                                .addGap(58, 58, 58)
                                .addComponent(btnbuscar)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbociudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbocargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btnbuscar)
                    .addComponent(btncancelar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbocargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocargoActionPerformed
        // TODO add your handling code here:
        mcombos mcombos1 =(mcombos) cbocargo.getSelectedItem(); //esto es por el mcombos
        idcargo = mcombos1.getID();
        // JOptionPane.showMessageDialog(null,idcargo,"OJO",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_cbocargoActionPerformed

    private void cbotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipoActionPerformed
        // TODO add your handling code here:
        mcombos mcombos1 =(mcombos) cbotipo.getSelectedItem(); //esto es por el mcombos
        idtipo = mcombos1.getID();
        // JOptionPane.showMessageDialog(null,idtipo,"OJO",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_cbotipoActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:

        txtnombre.requestFocus();
        llenar_combo();
        llenarciudad();
        llenacargos ();
        habilitar();
    }//GEN-LAST:event_btnnuevoActionPerformed
String accion ="metedatos";
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        // GUARDAR

        ConexionMySQL mysql = new ConexionMySQL(); //abre la conecxion
       Connection cn = mysql.Conectar(); //abre la conecxion
        

        String nom, apellido,direc,tel,correo, user, clave;
        Integer idciu,idcar,idtip;
        
        String guardartodo="";
        String mensaje;
        
        nom = txtnombre.getText();
        apellido = txtapellido.getText();
        direc = txtdireccion.getText();
        tel = txttelefono.getText ();
        correo = txtcorreo.getText ();
        user = txtuser.getText();
        clave = txtclave.getText();

        

       if (txtnombre.getText().isEmpty()||txtapellido.getText().isEmpty()||txtdireccion.getText().isEmpty()||txttelefono.getText().isEmpty()||txtcorreo.getText().isEmpty()|| txtuser.getText().isEmpty() || txtclave.getText().isEmpty()||idtipo.isEmpty()) //VALIDAMOS QUE LOS CAMPOS QUE NO ESTE VACIOS
       JOptionPane.showMessageDialog(null,"EXISTEN CAMPOS VACIOS","OJO",JOptionPane.PLAIN_MESSAGE);

        else if (accion.equals("metedatos"))
            
       
            
        {

 JOptionPane.showMessageDialog(null,idciudad,"OJO",JOptionPane.PLAIN_MESSAGE);
 JOptionPane.showMessageDialog(null,idcargo,"OJO",JOptionPane.PLAIN_MESSAGE);
 JOptionPane.showMessageDialog(null,idtipo,"OJO",JOptionPane.PLAIN_MESSAGE);

            idciu=Integer.parseInt(idciudad);
            idcar=Integer.parseInt(idcargo);
            idtip=Integer.parseInt(idtipo);
            
            
            
            guardartodo= "call guarda_empleados(?,?,?,?,?,?,?,?,?,?)";
            

            mensaje = "LOS DATOS SE HAN GUARDADO CORRECTAMENTE...";

            //txtuser.setText("");
            //txtclave.setText("");
            inhabilitar ();

        
        try
        {
            PreparedStatement pst = cn.prepareStatement(guardartodo); //preparo guardar//
            pst.setString(1, nom);
            pst.setString(2, apellido);
            pst.setString(3, direc);
            pst.setString(4, tel);
            pst.setString(5, correo);
            pst.setInt(6, idciu);
            pst.setInt(7, idcar);
            pst.setString(8, user);
            pst.setString(9, clave);
            pst.setInt(10, idtip);

            int n=0;
            n = pst.executeUpdate();

            if(n > 0)
            {
                JOptionPane.showMessageDialog(null, mensaje);
            }
        }
        catch (SQLException ex)
        {
            //JOptionPane.showMessageDialog(null, ex);
        }
    }                
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:

        //   buscar_usuario ingresar = new buscar_usuario();
        //     ingresar.setVisible(true);

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        inhabilitar ();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void cbociudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbociudadActionPerformed
        // TODO add your handling code here:
        mcombos mcombos1 =(mcombos) cbociudad.getSelectedItem(); //esto es por el mcombos
        idciudad = mcombos1.getID();

    }//GEN-LAST:event_cbociudadActionPerformed

        
        
    
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox cbocargo;
    private javax.swing.JComboBox cbociudad;
    private javax.swing.JComboBox cbotipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
