/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaventas;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import Conexion.ConexionMySQL;
import javax.swing.JOptionPane;
/**
 *
 * @author JULIAN
 */
public class modifica_cargos extends javax.swing.JInternalFrame {
 DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    String id;
    
    CallableStatement cts;
   ResultSet r;
   Connection cn;
   conexion conectar=new conexion();
    
    
    /**
     * Creates new form modifica_cargos
     */
    public modifica_cargos() {
        initComponents();
        llenar_combo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbocargo = new javax.swing.JComboBox();
        txtmdetalle = new javax.swing.JTextField();
        txtmsueldo = new javax.swing.JTextField();
        btmodifica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btmodifica1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificacion de Cargos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        cbocargo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbocargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccion" }));
        cbocargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocargoActionPerformed(evt);
            }
        });

        txtmdetalle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtmdetalle.setText("jTextField1");

        txtmsueldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtmsueldo.setText("jTextField1");

        btmodifica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmodifica.setText("MODIFICAR");
        btmodifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("DETALLE PUESTO");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("SUELDO");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Q.");

        btmodifica1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btmodifica1.setText("CERRAR");
        btmodifica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodifica1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtmdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btmodifica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btmodifica)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cbocargo, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbocargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtmsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmdetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmodifica)
                    .addComponent(btmodifica1))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void llenar_combo() {
            try {
    
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
                
                
           PreparedStatement pstmt = null;
            ResultSet rs = null;
            String llenar_combo="select id_cargo, CONCAT (descripcion,'- Q.',sueldo) as detalle  from cargo_empleado ";             
                      
                
pstmt = cn.prepareStatement(llenar_combo);
rs = pstmt.executeQuery();
modeloCombo.addElement(new mcombos("VER CARGOS","0"));
cbocargo.setModel(modeloCombo);
while (rs.next()) 
{
    modeloCombo.addElement(new mcombos(rs.getString("detalle"),rs.getString("id_cargo"))); //aca meto el id q jalo con mcombos
   //  cbocargo.setModel(modeloCombo);
       }
}
catch(Exception e) {}
            
   //hay q declarar antes  DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(); en la parte de clases publicas
            
  }  

    private void cbocargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocargoActionPerformed
        mcombos mcombos1 =(mcombos) cbocargo.getSelectedItem(); //esto es por el mcombos
        id = mcombos1.getID();

        btmodifica.setEnabled(true);
        txtmdetalle.setEnabled(true);
        txtmsueldo.setEnabled (true);

        txtmdetalle.setText("");
        txtmsueldo.setText("");

        //JOptionPane.showMessageDialog(null,id);
        JOptionPane.showMessageDialog(null,id,"EL PUESTO A EDITAR ES EL NUMERO:",JOptionPane.PLAIN_MESSAGE);
        
    
    }//GEN-LAST:event_cbocargoActionPerformed
 
    
    String accion = "modificar";
    private void btmodificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificaActionPerformed
        // TODO add your handling code here:

        ConexionMySQL mysql = new ConexionMySQL(); //abre la conecxion
        Connection cn = mysql.Conectar(); //abre la conecxion

        String des, sueldo;
        String modificar="";
        String mensaje = "";
        des =    txtmdetalle.getText();
        sueldo = txtmsueldo.getText();

        if (txtmdetalle.getText().isEmpty() || txtmsueldo.getText().isEmpty()) //VALIDAMOS QUE LOS CAMPOS QUE NO ESTE VACIOS
        JOptionPane.showMessageDialog(null,"EXISTEN CAMPOS VACIOS","OJO",JOptionPane.PLAIN_MESSAGE);

        else if (accion.equals("modificar"))
        {

            modificar = "call modificar_cargo (?, ?, ?)";
            mensaje = "LOS DATOS SE HAN ACTUALIZADO CORRECTAMENTE...";

            try
            {
                PreparedStatement pst = cn.prepareStatement(modificar); //preparo modificar//
                pst.setString(1, id);
                pst.setString(2, des);
                pst.setString(3, sueldo);

                int n = pst.executeUpdate();

                if(n > 0)
                {
                    JOptionPane.showMessageDialog(null, mensaje);
                }
            }
            catch (SQLException ex)
            {

                //JOptionPane.showMessageDialog(null, ex);
            }}

            btmodifica.setEnabled(false);
            txtmdetalle.setEnabled(false);
            txtmsueldo.setEnabled (false);

            txtmdetalle.setText("");
            txtmsueldo.setText("");
            
             
            this.dispose();
    }//GEN-LAST:event_btmodificaActionPerformed

    private void btmodifica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodifica1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btmodifica1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmodifica;
    private javax.swing.JButton btmodifica1;
    private javax.swing.JComboBox cbocargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmdetalle;
    private javax.swing.JTextField txtmsueldo;
    // End of variables declaration//GEN-END:variables
}
