
package sistemaventas;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author avalos
 */
public final class BuscarArticulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarArticulos
     */
    
    
      conexion conectar=new conexion();
      Connection cn;
      CallableStatement cts;
      ResultSet r;
      
      
    public BuscarArticulos() throws SQLException {
        initComponents();
        
        
         cn=conectar.conectado();
        cargar();
        
        
        
    }
 public void cargar(){
        
         DefaultTableModel tabla= new DefaultTableModel();
       try{
           
           
       tabla.addColumn("CODIGO");
       tabla.addColumn("DETALLE");
      // tabla.addColumn("MARCA");
      // tabla.addColumn("PROVEEDOR");    
       tabla.addColumn("PRECIO_COSTO");
       tabla.addColumn("PRECIO_VENTA");
       tabla.addColumn("STOCK");
       
       
         cts=cn.prepareCall("{ call MostrarProd }");
          r=cts.executeQuery();
                while (r.next())
                {
                       Object dato[]=new  Object[5];
                       for (int i=0; i<5; i++){
                       dato[i]=r.getString(i+1);

                                              }
                       tabla.addRow(dato);
                 }
                      this.jTable1.setModel(tabla);
     
       
       }catch (Exception e){}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarProduc = new javax.swing.JTextField();
        btBuscaProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItem1.setText("Actualizar");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exportar Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Busqueda de Articulos");

        jLabel2.setText("codigo producto:");

        btBuscaProd.setText("Buscar");
        btBuscaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaProdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscaProd)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscaProd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void Selecionaarticulo(){
       
         DefaultTableModel modelo = (DefaultTableModel) Factura.jtableDetalle.getModel();
        int row=jTable1.getSelectedRow();
        String COD=jTable1.getValueAt(row, 0).toString();
        String DETALLE=jTable1.getValueAt(row, 1).toString();
        String PREC_VENTA=jTable1.getValueAt(row, 2).toString();
        String PREC_COST=jTable1.getValueAt(row, 3).toString();
        
          
         int i=0; 
         i=i+1;
         Object[]  dato=new Object[4];
         
         
         
            dato[0]=COD;
            dato[1]=DETALLE;
            dato[2]=PREC_VENTA.toString();
            dato[3]=PREC_COST.toString();
            modelo.addRow(dato);
            
           Factura.jtableDetalle.setModel(modelo);
           Factura.jtableDetalle.editCellAt(row, 2);
           Factura.ajustarcolumnas();
            this.dispose();
           

         
       
 }
    private void btBuscaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaProdActionPerformed
        // TODO add your handling code here:
        String x=txtBuscarProduc.getText();
        DefaultTableModel tabla= new DefaultTableModel();
       try{
           
       tabla.addColumn("CODIGO");
       tabla.addColumn("DETALLE");
       tabla.addColumn("MARCA");
       tabla.addColumn("PROVEEDOR");    
       tabla.addColumn("PRECIO_COSTO");
       tabla.addColumn("PRECIO_VENTA");
       tabla.addColumn("STOCK");    
       
         cts=cn.prepareCall("{call BuscaProd(?)}");
         cts.setString(1, x);
         r=cts.executeQuery();
       
         while (r.next()){
         Object dato[]=new  Object[6];
         for (int i=0; i<6; i++){
         dato[i]=r.getString(i+1);

       }
       tabla.addRow(dato);
       }
       this.jTable1.setModel(tabla);

       }catch (Exception e){}
    }//GEN-LAST:event_btBuscaProdActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Selecionaarticulo();
        
                
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscaProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarProduc;
    // End of variables declaration//GEN-END:variables
}
